src/Entity/SearchByTitle.php
<?php

namespace App\Entity;

use App\Repository\SearchByTitleRepository;
use Doctrine\ORM\Mapping as ORM;

class SearchByTitle
{

    private $Title;

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

use DateTime;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user")
 * @UniqueEntity(fields="email", message="This email is already taken.")
 * @UniqueEntity(fields="username", message="This username is already taken.")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", unique=true)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(type="string", unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var Datetime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_login;

    /**
     * @var Datetime
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    public function getId(): int
    {
        return $this->id;
    }

    public function setFullName(string $fullName): void
    {
        $this->fullName = $fullName;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;

        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
        //
    }

    public function serialize(): string
    {
        return serialize([$this->id, $this->username, $this->password]);
    }

    public function unserialize($serialized): void
    {
        [$this->id, $this->username, $this->password] = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getLastLogin()
    {
        return $this->last_login;
    }

    public function setLastLogin($last_login): void
    {
        $this->last_login = $last_login;
    }

    public function getCreatedAt(): Datetime
    {
        return $this->created_at;
    }

    public function setCreatedAt(Datetime $created_at = null): void
    {
        $this->created_at = $created_at;
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
        $this->created_at = new Datetime();
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;
use App\Entity\Article;


use Doctrine\ORM\EntityManagerInterface;;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ArticleType;

class BlogController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */

    public function home(){
        return $this->render('home.html.twig');//appeler le fichier twig pour pouvoir l'afficher
    }
   
}

templates/blog/create.html.twig
{% extends 'base.html.twig' %} {#heritage de template base.html.twig#}

{% form_theme formArticle 'bootstrap_4_layout.html.twig' %} {#appel de theme de formulaire q'on a deja ajouter au fichie twig.yaml#}

{% block body %}

<h1>creation d'un article</h1>

{{ form_start(formArticle) }}

{{form_row(formArticle.title, {'attr': {'placeholder': "Titre de l'article"}})}}
{{form_row(formArticle.category)}}
{{form_row(formArticle.content, {'attr': {'placeholder': "tapez les contenue de l'article"}})}}
{{form_row(formArticle.image, {'attr': {'placeholder': "URL de l'image"}})}}


{{ form_widget(formArticle) }}

<button type="submit" class ="btn btn-success">
{% if editMode %}
 Enregistrer les modifiation
{% else %}
Ajouter l'article</button>
{% endif %}
{{form_end(formArticle)}}

{% endblock body %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name}}{% endblock %}

{% block body %}

<section class="articles">

  {% for article in articles %}
    <article>
        <h2>{{article.title}}</h2>
        <div class="metadata">ecrit le {{article.createdAt | date ('d/m/y')}}a {{article.createdAt | date('H:i')}}</div>
        <div class="content"></div>
        <div><img src="{{article.image}}" alt=""></div>
        <div>{{article.content}}</div>
        <div><a href="{{ path ('blog_show',{'id':article.id}) }}" class="btn btn-primary">lire la suite</a></div>
        
     </article>

   {% endfor %}
</section>

{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig'%}
{% block body %}
<article>
<h2>{{article.title}}</h2>
<div class="metadata">Ecrit le {{article.createdAt | date ('d/m/y')}} a {{article.createdAt | date('H:i')}} dans la categorie {{article.category.title}}</div>

<div><img src="{{article.image}}" alt=""></div>

<div class="content"><h4>desciption:</h4>  {{article.content|raw}}</div>
</article>
<section id="commentaires">
{% for comment in article.comments %}
<div class="comment">
<div class ="row">
<div class="col-3">
{{comment.author}} (<small>{{comment.createdAt | date ('d/m/y/ a h:i')}}</small>)
</div>
<div class="col">
{{comment.content | raw}}
</div>
</div>
</div>

{% endfor %}
{% endblock %}